---
title: MASS³ Monthly
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    title: Article Title is Capitalised
    subtitle: A short description of the article
    author: Author Name
    image: https://unsplash.it/1000/500/?random
    imageSource: Unsplash
    imageSourceURL: https://unsplash.it/
    category: Miscellaneous
    date: '2017-07-09'
    featured: false
    cover: false
    layout: article
    permalink: "/monthly/articles/:title"
description: Monash Advanced Science & Science Scholar Society News
url: "/monthly/"
editor: Shon Kolomoisky
edition: August 2017 Edition
website: http://masscubed.com/
twitter: 
facebook: http://www.facebook.com/groups/masscubed
email: mass3@monashclubs.org
color: "#111111"
